# =========================================================
# GLOBAL
# =========================================================
# ======================================
# DIRECTORIES
# ======================================

BASE_DIR="/opt/cameras/recordings"
LOG_DIR="/opt/cameras/logs"

# Lokalizacja do obliczeń astronomicznych
LATITUDE="52.2297"
LONGITUDE="21.0122"

# Zakres nagrywania względem wschodu/zachodu
# format: -1h / +30m / -15m itd.
SUN_OFFSET_BEFORE="-2h"
SUN_OFFSET_AFTER="+2h"

# Domyślny czas segmentu (sekundy)
DEFAULT_SEGMENT_TIME=900

# =========================================================
# LISTA KAMER
# =========================================================
CAMERAS=("POE1" "POE_BRAMA")

# =========================================================
# CAMERA: POE1
# =========================================================

CAM_POE1_ENABLED=1
CAM_POE1_NAME="POE1"

CAM_POE1_RTSP="rtsp://admin:kcbkcb2002@192.168.1.168:554/11"

# tryb nagrywania:
#   always  → nagrywaj zawsze
#   astro   → tylko wg zakresu astronomicznego
#   never   → nie nagrywaj
CAM_POE1_RECORD_MODE="always"

CAM_POE1_SEGMENT_TIME=3600

# =========================================================
# CAMERA: POE_BRAMA
# =========================================================

CAM_POE_BRAMA_ENABLED=1
CAM_POE_BRAMA_NAME="POE_BRAMA"

CAM_POE_BRAMA_RTSP="rtsp://ratp:wa463j@192.168.1.169:554/11"

# tryb nagrywania:
#   always  → nagrywaj zawsze
#   astro   → tylko wg zakresu astronomicznego
#   never   → nie nagrywaj
CAM_POE_BRAMA_RECORD_MODE="always"

CAM_POE_BRAMA_SEGMENT_TIME=3600

# =========================================================
# WIDOK / ROI (dla analizy)
# =========================================================

# full | window
CAM_POE1_VIEW_MODE="window"

CAM_POE1_LEFT=500
CAM_POE1_TOP=0
CAM_POE1_WIDTH=500
CAM_POE1_HEIGHT=880

CAM_POE1_ANALYSIS_SPEED=4
